apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jny2te8ud-go-gitops
  description: This is GitOps manifest for jny2te8ud-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: jny2te8ud-go
    janus-idp.io/tekton: jny2te8ud-go 
    backstage.io/kubernetes-id: jny2te8ud-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jny2te8ud-go
