apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jny2te8ud-go
  janus-idp.io/tekton: jny2te8ud-go
  backstage.io/kubernetes-id: jny2te8ud-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jny2te8ud-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
